JobMVC/Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JobMVC.Models
{
    public class ToDo
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(25)]
        public string ToDoName { get; set; }
        [MaxLength(100)]
        public string ToDoDescription { get; set; }
        public int AssignedTo { get; set; }
        public int HoursNeeded { get; set; }
        public bool IsCompleted { get; set; }
        public Employee Employees { get; set; }
    }
}

JobMVC/Controllers/ToDoController.cs
using JobMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JobMVC.Controllers
{
    public class ToDoController : Controller
    {
        ToDoDAL db = new ToDoDAL();
        public IActionResult Index()
        {
            List<ToDo> todos = db.GetTodos();
            return View(todos);
        }

        public IActionResult Search()
        {
            return View();
        }

        public IActionResult Result(int id)
        {
            ToDo t = db.GetTodo(id);
            return View(t);
        }

        public IActionResult Assign(int id)
        {
            ToDo t = db.GetTodo(id);
            return View(t);
        }
    }
}

JobMVC/Views/ToDo/Assign.cshtml
@model EmployeeToDoView

<h2>Assigner</h2>
<form method="post">
    <p>Select Employee</p>
    <select name="Id">
        @foreach (Employee e in Model.Employees)
        {
            <option value="@e.Id">@e.FullName</option>
        }
    </select>
    <input type="submit" />
</form>

JobMVC/Views/ToDo/Index.cshtml
@model IEnumerable<ToDo>

<h2>To Do List</h2>


@foreach (ToDo t in Model)
{
    <div style="border: 3px groove black">
        <p>Name: @t.ToDoName</p>
        <p>Description: @t.ToDoDescription</p>
        <p>Assigned To: @t.AssignedTo</p>
        <p>Is Completed?: @t.IsCompleted</p>
    </div>
}

JobMVC/Views/ToDo/Result.cshtml
@model ToDo

<div style="border: solid 2px black">
    <p>ToDo ID: @Model.Id</p>
    <p>ToDo Name: @Model.ToDoName</p>
    <p>ToDo Description: @Model.ToDoDescription</p>
    <p>Hours Needed: @Model.HoursNeeded</p>
    <p>Assigned To: @Model.AssignedTo</p>
    <p>Is It Completed?: @Model.IsCompleted</p>
    <a asp-action="Assign" asp-controller="ToDo" asp-route-id="@Model.Id"><p>Assign to Employee</p></a>
    <br />
</div>

JobMVC/Views/ToDo/Search.cshtml
@model ToDo

<p>Search by ToDo ID:</p>

<form asp-controller="ToDo" asp-action="Result">
    <p>
        <input type="number" name="Id" />
        <input type="submit" value="Search" />
    </p>
</form>